ALTER DATABASE scheduler CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE groups CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE schedule CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;